///////////////////////////////////////////////////////////
//  Product.cs
//  Implementation of the Class Product
//  Generated by Enterprise Architect
//  Created on:      17-Mar-2025 7:33:40 AM
//  Original author: johnl
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
namespace LicenseAssetManager.Models {
	public class Product {

		public Product(){

		}

		~Product(){

		}

		[Required(ErrorMessage = "Please specify a category")]
		public string Category{
			get;
			set;
		} = String.Empty;

		[Required(ErrorMessage = "Please enter a description")]
		public string Description{
			get;
			set;
		} = String.Empty;

		[Required(ErrorMessage = "Please enter a product name")]
		public string Name{
			get;
			set;
		} = String.Empty;

		[Required]
		[Range(0.01, double.MaxValue, ErrorMessage = "Please enter a positive price")]
		[Column(TypeName = "decimal(8, 2)")]
		public decimal Price{
			get;
			set;
		}

		public long? ProductID{
			get;
			set;
		}

	}//end Product

}//end namespace Models